/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HealthCalculator;
import java.awt.Color;

/**
 *
 * @author FAIS
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBTNbmr = new javax.swing.JButton();
        JBTNlbm = new javax.swing.JButton();
        JBTNbmi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMNITexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("guiMainMenu");
        setBackground(new java.awt.Color(0, 0, 0));

        JBTNbmr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBTNbmr.setText("BMR CALCULATOR");
        JBTNbmr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNbmrActionPerformed(evt);
            }
        });

        JBTNlbm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBTNlbm.setText("LBM CALCULATOR");
        JBTNlbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNlbmActionPerformed(evt);
            }
        });

        JBTNbmi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBTNbmi.setText("BMI CALCULATOR");
        JBTNbmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNbmiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CONTENTS");

        jMenu1.setText("File");

        JMNITexit.setText("Exit");
        JMNITexit.setToolTipText("");
        JMNITexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMNITexitActionPerformed(evt);
            }
        });
        jMenu1.add(JMNITexit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBTNbmi, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTNlbm, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTNbmr, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(JBTNbmi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBTNbmr, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBTNlbm, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBTNbmrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNbmrActionPerformed
        // TODO add your handling code here:
        jBMRcalculator BMR = new jBMRcalculator();
        BMR.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_JBTNbmrActionPerformed

    private void JBTNlbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNlbmActionPerformed
        // TODO add your handling code here:
        jLBMcalculator LBM = new jLBMcalculator();
        LBM.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_JBTNlbmActionPerformed

    private void JBTNbmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNbmiActionPerformed
        // TODO add your handling code here:
        jBMIcalculator BMI = new jBMIcalculator();
        BMI.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_JBTNbmiActionPerformed

    private void JMNITexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMNITexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JMNITexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTNbmi;
    private javax.swing.JButton JBTNbmr;
    private javax.swing.JButton JBTNlbm;
    private javax.swing.JMenuItem JMNITexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
